name: Deploy to GitHub Pages

jobs:
  build:
    env:
      ORCID_ACCESS_TOKEN: ${{ secrets.ORCID_ACCESS_TOKEN }}
      SECRET_TEST: ${{ secrets.SECRET_TEST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v0
